### ISSUE TITLE
The function `zoomdata.list_repos` misdetects repo settings

### ISSUE THREAD

**Issue by vutny** [Zoomdata/zoomdata-formula#149]
The function `zoomdata.list_repos`, when called with `compact=True` argument, returns wrong results if configured Zoomdata release is not ``latest``.
For example:
```yaml
  base_url: https://repo.zoomdata.com
  components:
  - stable
  gpgkey: https://repo.zoomdata.com/ZOOMDATA-GPG-KEY.pub
  release: tools
  repositories:
  - '3.7'
```

Expected result is:
```yaml
...
  release: '3.7'
  repositories:
  - tools
```

Other side effect reveals when legacy repositories are present in the system:
```yaml
  base_url: http://repo.zoomdata.com
  components:
  - stable
  - unstable
  gpgkey: https://repo.zoomdata.com/ZOOMDATA-GPG-KEY.pub
  release: latest
  repositories:
  - tools
  - tools
  - '3.1'
```
